FROM python:3.9

# Set workdir
WORKDIR /src

# Install dependencies
COPY requirements.txt /src/requirements.txt
RUN pip install --no-cache-dir --upgrade -r requirements.txt

# Expose port
EXPOSE 8080

# Copy app and set python path
COPY text_check /src/text_check
CMD ["uvicorn", "text_check.app:app", "--host", "0.0.0.0", "--port", "8080"]