name: demo
on:
  push:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed
  pull_request:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed

jobs:
  check_reqs_change:
    name: Check if requirements.txt or requirements-freeze.txt is changed
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
      
      - name: Check if requirements.txt or requirements-freeze.txt is changed
        id: check_reqs_change
        run: |
          $req_diff = git diff HEAD HEAD~1 --no-patch --exit-code requirements.txt
          if [ $req_diff==1 ]; then
            # check if requirements-freeze.txt was changed and set it to a variable
            $req_freeze_diff = git diff HEAD HEAD~1 --no-patch --exit-code requirements-freeze.txt
            if [ $req_freeze_diff!=1 ]; then
              echo "Requirements.txt was changed but requirements-freeze.txt was not changed"
              exit 1
            fi
          fi



