name: demo
on:
  push:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed
  pull_request:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed

jobs:
  check_reqs_changed:
    name: Check if requirements.txt and requirements-freeze.txt were changed
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check if requirements.txt was changed
        id: check_reqs_changed
        run: |
          if [[ $(git diff HEAD HEAD~1 --no-patch --exit-code requirements.txt) -gt 0 ]]; then
            echo "CHANGED=true" >> $GITHUB_OUTPUT
            echo "requirements.txt was changed"
          else
            echo "CHANGED=false" >> $GITHUB_OUTPUT
            echo "requirements.txt was not changed"
          fi
      
      - name: Check if requirements-freeze.txt was changed
        id: check_reqs_freeze_change
        if: steps.check_reqs_changed.outputs.CHANGED == 'true'
        run: |
          if [[ $(git diff HEAD~1 HEAD --name-only | grep -c "requirements-freeze.txt") -gt 0 ]]; then
            echo "requirements-freeze.txt was changed"
          else
            echo "requirements-freeze.txt was not changed"
            exit 1
          fi