name: demo
on:
  push:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed
  pull_request:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed

jobs:
  check_reqs_change:
    name: Check if requirements.txt or requirements-freeze.txt is changed
    runs-on: ubuntu-latest
    continue-on-error: false

    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check if requirements.txt is changed
        id: check_reqs_change
        run: |
          echo "Checking if requirements.txt is changed"
          git diff HEAD~1 HEAD --no-patch --exit-code requirements.txt
          echo "$?"
