name: demo
on:
  push:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed
  pull_request:
    branches:
        - 'main'
    paths:
        - "text_check/**" # check if any file in text_check folder is changed
        - "requirements.txt" # check if requirements.txt is changed
        - "requirements-freeze.txt" # check if requirements-freeze.txt is changed

jobs:
  check_reqs_change:
    name: Check if requirements.txt or requirements-freeze.txt is changed
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Repo
        id: checkout_repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check if requirements.txt is changed
        id: check_reqs_change
        uses: tj-actions/verify-changed-files@v12
        with:
          files: |
            requirements.txt
            requirements-freeze.txt
      
      - name: Check if requirements-freeze.txt is changed
        id: check_freeze_change
        if: steps.check_reqs_change.outputs.files_changed == 'true'
        run: |
          if contains(steps.check_reqs_change.outputs.files_changed, 'requirements-freeze.txt')
            echo "::set-output name=freeze_changed::true"
          else
            echo "requirements-freeze.txt is not changed"
            exit 1
        
        

        


